### ISSUE TITLE
library build error

### ISSUE THREAD

**Issue by andatt** [dsoprea/CTesseract#1]
Hi 

I am getting the following error when running the make command on building the library:

[ 25%] Building CXX object CMakeFiles/ctesseract.dir/ctess_string.cpp.o
/home/andrew/Downloads/CTesseract-master/ctess_string.cpp: In function ‘const char\* tess_string_get_char_array(tess_string_t_)’:
/home/andrew/Downloads/CTesseract-master/ctess_string.cpp:7:29: error: invalid use of incomplete type ‘class STRING’
In file included from /home/andrew/Downloads/CTesseract-master/include/ctesseract/ctess_string.h:4:0,
                 from /home/andrew/Downloads/CTesseract-master/ctess_string.cpp:1:
/usr/include/tesseract/baseapi.h:44:7: error: forward declaration of ‘class STRING’
/home/andrew/Downloads/CTesseract-master/ctess_string.cpp: In function ‘void tess_string_free(tess_string_t_)’:
/home/andrew/Downloads/CTesseract-master/ctess_string.cpp:12:18: error: possible problem detected in invocation of delete operator: [-Werror]
/home/andrew/Downloads/CTesseract-master/ctess_string.cpp:12:18: error: invalid use of incomplete type ‘class STRING’ [-Werror]
In file included from /home/andrew/Downloads/CTesseract-master/include/ctesseract/ctess_string.h:4:0,
                 from /home/andrew/Downloads/CTesseract-master/ctess_string.cpp:1:
/usr/include/tesseract/baseapi.h:44:7: error: forward declaration of ‘class STRING’ [-Werror]
/home/andrew/Downloads/CTesseract-master/ctess_string.cpp:12:18: note: neither the destructor nor the class-specific operator delete will be called, even if they are declared when the class is defined
/home/andrew/Downloads/CTesseract-master/ctess_string.cpp: In function ‘const char\* tess_string_get_char_array(tess_string_t_)’:
/home/andrew/Downloads/CTesseract-master/ctess_string.cpp:8:1: error: control reaches end of non-void function [-Werror=return-type]
cc1plus: all warnings being treated as errors
make[2]: *_\* [CMakeFiles/ctesseract.dir/ctess_string.cpp.o] Error 1
make[1]: **\* [CMakeFiles/ctesseract.dir/all] Error 2
make: **\* [all] Error 2

**Comment by dsoprea** [comment]
An "incomplete type" is one that hasn't been formally defined (e.g. "class ABC;" or "struct DEF;"). This is usually done because it's completely defined in a source-file (not a header), but you need at least _something_ to be defined so that you can use it. Obviously, you're relying on it to be there when the program is linked. I don't like this practice, but it's not mine to change.

In _ctess_string.cpp_, I'm referring to a type "tess_string_t", which is defined (in _ctess_string.h_) to wrap type "_STRING_", a Tesseract object defined in _baseapi.h_. The problem is that it's declared as "class STRING;", and actually defined in the Tesseract library (libtesseract). However, you're having a problem that I can't simulate on my Ubuntu, or OS X.

Make sure the headers and source are the same version. What version of Tesseract are you using?

**Comment by andatt** [comment]
I'm using Tesseract 3.02.02. I started again from a clean os install (wattos) on a different machine and everything built sucessfuly and working this time. Not sure what happened before but I will keep playing with my crunchbang install to see if it's fixable.

**Comment by dsoprea** [comment]
Glad to hear it. Let me know if I can be of further assistance.

Dustin
